### ISSUE TITLE
Pre-calculated color histograms of the collection for the color reduction

### ISSUE THREAD

**Issue by ashleyjester** [sul-cidr/histonets#55]

**Comment by versae** [comment]
We can use RMagick's [`color_histogram`](https://rmagick.github.io/image1.html#color_histogram).

**Comment by csbailey5t** [comment]
This issue was moved to sul-cidr/histonets-cv#80

**Comment by mejackreed** [comment]
Oops.. reopening.. as I think I was confused about posterize

**Comment by csbailey5t** [comment]
I moved this over to the histonets-cv repo since it seemed like a primarily python thing. 

After talking to @versae, it's going to be a combo. If we could use ruby/rails with rmagick to create the histogram for the collection as each image is uploaded, that would then be passed to the python script. If we can't get it working through rails, we could do it through python.

**Comment by mejackreed** [comment]
Well it still needs to be implemented in the UI, no?
